cols = ['name','abbreviation',
        'average_age','games_played', 'goals_for','goals_against','wins', 'losses', 
        'overtime_losses', 
       'points', 'EWP','PW','PL','PW Season','PL Season','Ahead/Behind',
       'penalty_killing_percentage','points_percentage','power_play_goals', 
       'power_play_goals_against','power_play_opportunities',
       'power_play_opportunities_against',
       'power_play_percentage','rank','save_percentage',
       'shooting_percentage','short_handed_goals',
       'short_handed_goals_against','shots_against','shots_on_goal',
       'simple_rating_system','strength_of_schedule']