seasonCols = ['name','abbreviation',
        'average_age','games_played', 'goals_for','goals_against','wins', 'losses', 
        'overtime_losses', 'GF/G','GA/G','Goal Diff',
       'points', 'EWP','PW','PL','PW Season','PL Season','Ahead/Behind',
       'penalty_killing_percentage','points_percentage','power_play_goals', 
       'power_play_goals_against','PP Diff','power_play_opportunities',
       'power_play_opportunities_against','PPO Diff',
       'power_play_percentage','rank','save_percentage',
       'shooting_percentage','short_handed_goals',
       'short_handed_goals_against','shots_against','shots_on_goal','Shot Diff',
       'simple_rating_system','strength_of_schedule']

careerCols = ['name','adjusted_assists',
 'adjusted_goals',
 'adjusted_goals_against_average',
 'adjusted_goals_created',
 'adjusted_points',
 'age',
 'assists',
 'average_time_on_ice',
 'blocks_at_even_strength',
 'corsi_against',
 'corsi_for',
 'corsi_for_percentage',
 'defensive_point_shares',
 'defensive_zone_start_percentage',
 'even_strength_assists',
 'even_strength_goals',
 'even_strength_goals_allowed',
 'even_strength_save_percentage',
 'even_strength_shots_faced',
 'faceoff_losses',
 'faceoff_percentage',
 'faceoff_wins',
 'fenwick_against',
 'fenwick_for',
 'fenwick_for_percentage',
 'game_winning_goals',
 'games_played',
 'giveaways',
 'goal_against_percentage_relative',
 'goalie_point_shares',
 'goals',
 'goals_against',
 'goals_against_average',
 'goals_against_on_ice',
 'goals_created',
 'goals_for_on_ice',
 'goals_saved_above_average',
 'height',
 'hits_at_even_strength',
 'league',
 'losses',
 'minutes',
 'offensive_point_shares',
 'offensive_zone_start_percentage',
 'pdo',
 'penalties_in_minutes',
 'plus_minus',
 'point_shares',
 'points',
 'power_play_assists',
 'power_play_goals',
 'power_play_goals_against_on_ice',
 'power_play_goals_allowed',
 'power_play_goals_for_on_ice',
 'power_play_save_percentage',
 'power_play_shots_faced',
 'quality_start_percentage',
 'quality_starts',
 'really_bad_starts',
 'relative_corsi_for_percentage',
 'relative_fenwick_for_percentage',
 'save_percentage',
 'save_percentage_on_ice',
 'saves',
 'season',
 'shooting_percentage',
 'shooting_percentage_on_ice',
 'shootout_attempts',
 'shootout_goals',
 'shootout_misses',
 'shootout_percentage',
 'short_handed_assists',
 'short_handed_goals',
 'short_handed_goals_allowed',
 'short_handed_save_percentage',
 'short_handed_shots_faced',
 'shots_against',
 'shots_on_goal',
 'shutouts',
 'takeaways',
 'team_abbreviation',
 'ties_plus_overtime_loss',
 'time_on_ice',
 'time_on_ice_even_strength',
 'total_goals_against_on_ice',
 'total_goals_for_on_ice',
 'total_shots',
 'weight',
 'wins',
 'year']

changes = {'wins':'W','losses':'L',
                                        'overtime_losses':'OL',
                                        'games_played':'GP',
                                        'average_age':'AvAge',
                                        'goals_for':'GF',
                                        'points':'PTS',
                                        'penalty_killing_percentage':'PK%',
                                        'points_percentage':'PTS%',
                                        'power_play_goals':'PP',
                                        'power_play_goals_against':'PPA',
                                        'power_play_opportunities':'PPO',
                                        'power_play_opportunities_against':'PPOA',
                                        'power_play_percentage':'PP%',
                                        'rank':'Rank',
                                        'save_percentage':'SV%',
                                        'shooting_percentage':'S%',
                                        'short_handed_goals':'SH',
                                        'short_handed_goals_against':'SHA',
                                        'shots_against':'SA',
                                        'shots_on_goal':'S',
                                        'simple_rating_system':'SRS',
                                        'strength_of_schedule':'SOS',
                                        'goals_against':'GA'
                                        }

correctNames = ['Team',
 'Abbreviation',
 'AvAge',
 'GP',
 'GF',
 'GA',
 'W',
 'L',
 'OL',
 'GA/G',
 'GF/G',
 'Goal Diff',
 'PTS',
 'EWP',
 'PW',
 'PL',
 'PW Season',
 'PL Season',
 'Ahead/Behind',
 'PK%',
 'PTS%',
 'PP',
 'PPA',
 'PP Diff',
 'PPO',
 'PPOA',
 'PPO Diff',
 'PP%',
 'Rank',
 'SV%',
 'S%',
 'SH',
 'SHA',
 'SA',
 'S',
 'Shot Diff',
 'SRS',
 'SOS']