cols = ['name','abbreviation',
        'average_age','games_played', 'goals_for','goals_against','wins', 'losses', 
        'overtime_losses', 'GF/G','GA/G','Goal Diff',
       'points', 'EWP','PW','PL','PW Season','PL Season','Ahead/Behind',
       'penalty_killing_percentage','points_percentage','power_play_goals', 
       'power_play_goals_against','PP Diff','power_play_opportunities',
       'power_play_opportunities_against','PPO Diff',
       'power_play_percentage','rank','save_percentage',
       'shooting_percentage','short_handed_goals',
       'short_handed_goals_against','shots_against','shots_on_goal','Shot Diff',
       'simple_rating_system','strength_of_schedule']

changes = {'wins':'W','losses':'L',
                                        'overtime_losses':'OL',
                                        'games_played':'GP',
                                        'average_age':'AvAge',
                                        'goals_for':'GF',
                                        'points':'PTS',
                                        'penalty_killing_percentage':'PK%',
                                        'points_percentage':'PTS%',
                                        'power_play_goals':'PP',
                                        'power_play_goals_against':'PPA',
                                        'power_play_opportunities':'PPO',
                                        'power_play_opportunities_against':'PPOA',
                                        'power_play_percentage':'PP%',
                                        'rank':'Rank',
                                        'save_percentage':'SV%',
                                        'shooting_percentage':'S%',
                                        'short_handed_goals':'SH',
                                        'short_handed_goals_against':'SHA',
                                        'shots_against':'SA',
                                        'shots_on_goal':'S',
                                        'simple_rating_system':'SRS',
                                        'strength_of_schedule':'SOS',
                                        'goals_against':'GA'
                                        }

correctNames = ['Team',
 'Abbreviation',
 'AvAge',
 'GP',
 'GF',
 'GA',
 'W',
 'L',
 'OL',
 'GA/G',
 'GF/G',
 'Goal Diff',
 'PTS',
 'EWP',
 'PW',
 'PL',
 'PW Season',
 'PL Season',
 'Ahead/Behind',
 'PK%',
 'PTS%',
 'PP',
 'PPA',
 'PP Diff',
 'PPO',
 'PPOA',
 'PPO Diff',
 'PP%',
 'Rank',
 'SV%',
 'S%',
 'SH',
 'SHA',
 'SA',
 'S',
 'Shot Diff',
 'SRS',
 'SOS']